# Generated by Django 2.2.1 on 2019-06-15 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sociat', '0005_auto_20190602_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=264),
            preserve_default=False,
        ),
    ]
