# Generated by Django 2.2.1 on 2019-06-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociat', '0006_register_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='password',
        ),
    ]
