# Generated by Django 2.2.1 on 2019-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociat', '0007_remove_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='pas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
