# Generated by Django 2.2.1 on 2019-07-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='Title',
            field=models.CharField(max_length=264),
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.CharField(max_length=264),
        ),
    ]
